name: Deploy to Alwaysdata

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ssh1.alwaysdata.com
          username: excellencedigital
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/excellencedigital/laravel

            # Synchronisation propre du code
            git fetch origin main
            git reset --hard origin/main

            # Backend Laravel
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Frontend
            npm install
            npm run build